version: '3.8'
services:
    php:
        build:
            context: ./docker/apache
            dockerfile: Dockerfile
        image: php:limpmais
        volumes:
            - '.:/var/www/html'
            - './docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf'
            - './php.ini-development:/usr/local/etc/php/php.ini'
        networks:
            - limpmais
            - traefik
        depends_on:
            - postgres
        labels:
          traefik.enable: true
          traefik.http.routers.limpmais.rule: Host(`limpmais.jf`)
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        networks:
            - limpmais
networks:
    limpmais:
        name: limpmais
    traefik:
        external: true
